### ISSUE TITLE
How to modify the overall height of the model in slpk file？

### ISSUE THREAD

**Issue by xby020** [Esri/i3s-spec#13]
Because some software can't change the height when exporting the SLPK file, the height of the model is inconsistent when multiple SLPK files are imported into the same software. How can the overall height of the model (including all nodes) be changed by modifying the SLPK file?

**Comment by pengfei666** [comment]
Do you want to modify it manually? It seems it is hard to change the overall height.

You need to change all the node's center at same time. 

According to the spec, you can modify the mbs property. The third parameter in mbs generally represent the node's height.

You could traverse all the node index document, add a same bias height for the third number in mbs. 

Hope it helps.

**Comment by sreinhard** [comment]
this problem usually happens when you mix different vertical coordinate systems. Try to make sure all your different software packages agree on the vertical coordinate system. If that does not help, the viewers usually have the option to apply a vertical offset to an existing scene service.

As a last resort, you can try @pengfei666's suggestion or add the following definition to the layer document in the slpk (same as configuring a vertical offset in the viewer):
```
"elevationInfo": {
  "mode": "absoluteHeight",
  "offset": 123.45
}
```

**Comment by saadat2930** [comment]
How do we add vertical shift/offset in ArcGIS runtime dot net (WPF) application while loading the model locally? I cant find any material on that, please let me know if i am missing anything.

 ```
Uri _serviceUri = new System.Uri(@"D:\Projects\test\model\lod75.slpk");
ArcGISSceneLayer sceneLayer = new ArcGISSceneLayer(_serviceUri);
 myScene.OperationalLayers.Add(sceneLayer);

```
