### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by Shtirlic81** [Esri/i3s-spec#33]
Hello, 

I'v got some sample of the I3S format, and there the actual image size is 512x1024.
x size is 512.

So in order to know the y size I need to decode the image.

I need this information in case the texture is bigger than I need and in this case I won't use it.

Is it possible to add y size field to the format?

Thanks.

**Comment by jfoster126** [comment]
Hi @Shtirlic81 , 

In spec version 1.6, the [image](https://github.com/Esri/i3s-spec/blob/master/docs/1.7/image.cmn.md) also includes the `length` property, which is used to find the `y` dimension.  Please note that the 1.7 spec version uses `texelCountHint` in the [meshMaterial](https://github.com/Esri/i3s-spec/blob/master/docs/1.7/meshMaterial.cmn.md) instead of image.

**Comment by jfoster126** [comment]
Hi @Shtirlic81 , 

If you are using 1.6, the height of the image is not available. Only the width and the compressed length are available. 

1.7 spec version uses `texelCountHint` in the [meshMaterial](https://github.com/Esri/i3s-spec/blob/master/docs/1.7/meshMaterial.cmn.md) instead of image, which is `width x height`, which may be enough to determine if the image is too large for your use case. 

Please let us know if you have use case where the height is important instead of the product.

**Comment by Shtirlic81** [comment]
OK, thanks
