### ISSUE TITLE
A few question regarding to 1.7 Update.

### ISSUE THREAD

**Issue by intckarl** [Esri/i3s-spec#34]
By comparing 1.6 and 1.7, one could find that they are basic the same. All different I can find is 1.7 now support Draco compress and nodepages.

Even in ArcGIS Pro 2.4, it still only create version 1.6. One have to use the converter to update to 1.7.

By studying the outcome, I found that 1.7 make leaf node much smaller, with produce more nodes in total, thus make the result SLPK much larger.

Also, I found a hashtable in both 3d object and Integrated Mesh, which you failed to mention in the doc.

So far one could tell that 1.7 cut the nodes smaller and draco it more smaller to speed up transmitting, and use nodepages and hashtable to speed up querying. but in practice, it cause the server overwhelmed by sending too much requests. And actually make it slower to load.

Please give me an answer, Thank you.

**Comment by jfoster126** [comment]
Hi @intckarl , thank you for your feedback. 

You are correct, the main changes for 1.7 are Draco and `nodepages`. The new additions in 1.7 are summarized in the [What's New](https://github.com/Esri/i3s-spec#whats-new) section in the ReadMe. Since 1.7 is backwards compatible with 1.6, deprecated items in 1.7 still need to be included in order to support 1.6 clients. E.g. The `sharedResources` is deprecated, but still included in a 1.7 Scene Layer Package (slpk).  

1.6 and 1.7 slpk have the same number of nodes.  The 1.7 nodes are organized into `nodepages`.  More details about `nodepages` can be found in the [I3S format doc](https://github.com/Esri/i3s-spec/blob/master/format/Indexed%203d%20Scene%20Layer%20Format%20Specification.md#node-paging-and-the-node-page-index) and in the [nodepage definition](https://github.com/Esri/i3s-spec/blob/master/docs/1.7/nodePages.cmn.md).

ArcGIS Pro 2.4 writes out version 1.7 for 3D Objects when creating slpk. You can verify this by opening the slpk to finding the nodepages folder, or using the `-i` option in the new [i3s_converter.exe](https://github.com/Esri/i3s-spec/blob/master/i3s_converter/i3s_converter_ReadMe.md).  In ArcGIS Pro 2.5, we plan to output 1.7 when caching on the server and move the other slpk profiles to 1.7.

The hash table documentation in 1.7 is the same as the hash table in 2.0.  The 1.7 can be [found here](https://github.com/Esri/i3s-spec/blob/master/docs/1.7/slpk_hashtable.cmn.md).  We forgot to include the copy in the 1.7 documents in the initial push, good catch.

**Comment by intckarl** [comment]
@jfoster126  Hello, thank you for reply.
In my test, I use ArcGIS Pro 2.4 and only have 1.6 produced, as below. You can see the time, I just do it again this morning.
![222](https://user-images.githubusercontent.com/14276240/60777238-dfcb7d00-a163-11e9-95f4-3b768e71563f.jpg)

Also, when I use the converter to update some existing 1.6 slpk to 1.7, the file became much larger. 
![QQ截图20190708091754](https://user-images.githubusercontent.com/14276240/60777294-3042da80-a164-11e9-9659-ed7beb7152c7.jpg)
That is 3d object. also I got an Integrated Mesh whose 1.6 is 7.8GB and 1.7 is 18.3GB


But you are correct about 1.6 and 1.7 slpk have the same number of nodes. And I didn't find what cause the extra file amount. 


One more question, is 1.7 only appliable to Enterprise 10.7.1 or also be compatible with 10.7? I mean the hash table and node pages that speed up part.

**Comment by intckarl** [comment]
![image](https://user-images.githubusercontent.com/14276240/60783179-2c22b700-a17c-11e9-89f0-14eb5280b321.png)

That said Integrated Mesh slpk

**Comment by jfoster126** [comment]
Hi @intckarl , 

It's possible that the regkeys didn't get cleaned up correctly when installing Pro 2.4. In the Registry Editor, please delete the folder:

`HKEY_CURRENT_USER\Software\ESRI\ArcGISPro`

**Comment by Tamrat-B** [comment]
Hi @intckarl,

you mentioned:

> ![image](https://user-images.githubusercontent.com/14276240/60783179-2c22b700-a17c-11e9-89f0-14eb5280b321.png)
> 
> That said Integrated Mesh slpk

you also wrote:

> That is 3d object. also I got an Integrated Mesh whose 1.6 is 7.8GB and 1.7 is 18.3GB
> 
> But you are correct about 1.6 and 1.7 slpk have the same number of nodes. And I didn't find what cause the extra file amount.

The reason why the IntegratedMesh at 1.7 is much bigger than the input 1.6 IntegratedMesh is most likely because the original Integrated Mesh content **did not** include compressed textures (for example in the form of [DXT ]. See [here](https://github.com/Esri/i3s-spec/blob/ce6ab0f8cbe4980835d1bedeb83839b98a7dc178/docs/1.6/textureDefinition.cmn.md) for 1.6 definition of supported textures and [here](https://github.com/Esri/i3s-spec/blob/ce6ab0f8cbe4980835d1bedeb83839b98a7dc178/docs/1.7/textureSetDefinitionFormat.cmn.md) for 1.7 definition.

You can verify this by navigating to your SLPK using any archive viewer (eg. 7zip). You'll notice that in the 1.7 version you have both jpg and compressed texture in dxt format (dds container) as below.

![image](https://user-images.githubusercontent.com/12946567/63059306-e7d5b580-bea3-11e9-8559-ef0f7570d3c3.png)

Most likely in your 1.6 input the dds texture is missing and hence the reason for the significant difference in size. 

Hope this helps.
