### ISSUE TITLE
SharedResource

### ISSUE THREAD

**Issue by Shtirlic81** [Esri/i3s-spec#37]
Hi,

In SharedResource there is a materialDefinitions field, and the explanation of it is:
"Materials describe how a Feature or a set of Features is to be rendered."

So it suppose to be an array of material definitions (materialDefinition[])?

**Comment by jfoster126** [comment]
Hi @Shtirlic81 , 

We don't support multiple materials per node. Since we have one "shared" resource per node, we can't have multiple materials listed here. 

Please note that [materialDefinition](https://github.com/Esri/i3s-spec/blob/master/docs/1.7/materialDefinition.cmn.md) in the [sharedResources](https://github.com/Esri/i3s-spec/blob/master/docs/1.7/sharedResource.cmn.md) are deprecated in 1.7. The [materialDefinition](https://github.com/Esri/i3s-spec/blob/master/docs/1.7/materialDefinitions.cmn.md) in 1.7 is cleaner and easier to use.
