### ISSUE TITLE
i3s version1.7 is fit for arcgis enterprise10.71?

### ISSUE THREAD

**Issue by giserHacter** [Esri/i3s-spec#45]
I found it wasn't as fast as the authorities said it would be 2-4 times in arcgis portal10.7,so,i want to know what arcgis portal version is fit for i3s 1.7?

**Comment by giserHacter** [comment]
when i use the i3s_converter.exe and i find it break.my slpk data is i3s1.6 and producted by arcgis pro2.3
here is the error information:Warning:Mimimum bounding sphere radius for node nodes/19-0-0-0-0-0-1-1-2/3dNodeIndexDocument must be greater than 0.0（got:0.00001）

**Comment by jfoster126** [comment]
Hi @giserHacter , 

I3S 1.7 is supported in ArcGIS Pro 2.4 and ArcGIS Online, as mentioned in the [What's New](https://github.com/Esri/i3s-spec#version-17) section in the ReadMe.  Since 1.7 is backwards compatible, other clients utilize the 1.6 components, so you will not see a performance increase. ArcGIS Enterprise is scheduled to support I3S 1.7 in 10.8.

Warnings are ok from the converter, and should draw correctly in all clients.  When upgrading, the converter compares the details of the SLPK to the spec.  If something doesn't match, then a warning is included in the log.  If you have access to the source data, you can try to adjust it to be compliant with the spec.  The converter will fail with an error, not a warning, if it can't be upgraded or validated.

**Comment by giserHacter** [comment]
hello,jfoster
       Can the i3s1.7  work if i use arcgis api for js 4.12?

**Comment by jfoster126** [comment]
I3S 1.7 will work in the JavaScript API, because it is backwards compatible, but the JavaScript API will not utilize the 1.7 aspects of the scene layer.

**Comment by rvargasESRI** [comment]
Hello @giserHacter 

Please use arcgis js api 4.16, as this is the latest version and fully supports i3s 1.7.
