### ISSUE TITLE
The limited of i3s node size？

### ISSUE THREAD

**Issue by AlsumDea** [Esri/i3s-spec#75]
hi devs

How big can a node size be？I'd like to know the limitation of a node size in slpk file（gigabytes？terabytes？）
Specifically, the geometry binary file size / feature attribute binary file size / texture resources size ...

thanks.

**Comment by sreinhard** [comment]
Hi AlsumDea,

The recommended total size for a single node is around 1 megabyte. Bigger nodes tend to take a long time to load, which leads to a bad user experience.

There is no specific maximum, however I really recommend against nodes bigger than 100mb, since some clients (browser, mobile) will have trouble handling them.

I hope this helps,
Simon

**Comment by AlsumDea** [comment]
> Hi AlsumDea,
> 
> The recommended total size for a single node is around 1 megabyte. Bigger nodes tend to take a long time to load, which leads to a bad user experience.
> 
> There is no specific maximum, however I really recommend against nodes bigger than 100mb, since some clients (browser, mobile) will have trouble handling them.
> 
> I hope this helps,
> Simon

Thank u for your reply！
